In [31]:
import polars as pl

In [32]:
mimic3source = "/home/cararc/data/mimic-iii-1.4/"
prescriptions = pl.read_csv(
    mimic3source + "PRESCRIPTIONS.csv",
    separator=",",
    schema_overrides={"GSN": pl.Utf8},
    infer_schema_length=10000
)

In [35]:
prescriptions = prescriptions.with_columns(
    pl.struct(["STARTDATE", "DRUG", "GSN", "NDC", "PROD_STRENGTH", "DOSE_VAL_RX", "DOSE_UNIT_RX"]).alias("prescription")
)
prescriptions = prescriptions.group_by(["SUBJECT_ID", "HADM_ID"]).agg(
    pl.col("prescription")
)
# prescriptions = prescriptions.drop(["STARTDATE", "DRUG", "GSN", "NDC", "PROD_STRENGTH", "DOSE_VAL_RX", "DOSE_UNIT_RX"])

In [36]:
prescriptions.head()

shape: (5, 3)
┌────────────┬─────────┬─────────────────────────────────┐
│ SUBJECT_ID ┆ HADM_ID ┆ prescription                    │
│ ---        ┆ ---     ┆ ---                             │
│ i64        ┆ i64     ┆ list[struct[7]]                 │
╞════════════╪═════════╪═════════════════════════════════╡
│ 5285       ┆ 127903  ┆ [{"2202-09-29 00:00:00","Metop… │
│ 30292      ┆ 113876  ┆ [{"2199-03-04 00:00:00","quini… │
│ 11242      ┆ 188157  ┆ [{"2154-11-11 00:00:00","0.9% … │
│ 20310      ┆ 144150  ┆ [{"2175-08-28 00:00:00","Succi… │
│ 18101      ┆ 150827  ┆ [{"2118-02-23 00:00:00","Altep… │
└────────────┴─────────┴─────────────────────────────────┘

In [ ]:
admissions = pl.read_csv(
    mimic3source + "ADMISSIONS.csv",
    separator=",",
)

In [ ]:
admissions.head()

shape: (5, 19)
┌────────┬────────────┬─────────┬────────────┬───┬────────────┬────────────┬───────────┬───────────┐
│ ROW_ID ┆ SUBJECT_ID ┆ HADM_ID ┆ ADMITTIME  ┆ … ┆ EDOUTTIME  ┆ DIAGNOSIS  ┆ HOSPITAL_ ┆ HAS_CHART │
│ ---    ┆ ---        ┆ ---     ┆ ---        ┆   ┆ ---        ┆ ---        ┆ EXPIRE_FL ┆ EVENTS_DA │
│ i64    ┆ i64        ┆ i64     ┆ str        ┆   ┆ str        ┆ str        ┆ AG        ┆ TA        │
│        ┆            ┆         ┆            ┆   ┆            ┆            ┆ ---       ┆ ---       │
│        ┆            ┆         ┆            ┆   ┆            ┆            ┆ i64       ┆ i64       │
╞════════╪════════════╪═════════╪════════════╪═══╪════════════╪════════════╪═══════════╪═══════════╡
│ 21     ┆ 22         ┆ 165315  ┆ 2196-04-09 ┆ … ┆ 2196-04-09 ┆ BENZODIAZE ┆ 0         ┆ 1         │
│        ┆            ┆         ┆ 12:26:00   ┆   ┆ 13:24:00   ┆ PINE       ┆           ┆           │
│        ┆            ┆         ┆            ┆   ┆            ┆ OVERDOSE   ┆           ┆           │
│ 22     ┆ 23         ┆ 152223  ┆ 2153-09-03 ┆ … ┆ null       ┆ CORONARY   ┆ 0         ┆ 1         │
│        ┆            ┆         ┆ 07:15:00   ┆   ┆            ┆ ARTERY DIS ┆           ┆           │
│        ┆            ┆         ┆            ┆   ┆            ┆ EASE\CORON ┆           ┆           │
│        ┆            ┆         ┆            ┆   ┆            ┆ A…         ┆           ┆           │
│ 23     ┆ 23         ┆ 124321  ┆ 2157-10-18 ┆ … ┆ null       ┆ BRAIN MASS ┆ 0         ┆ 1         │
│        ┆            ┆         ┆ 19:34:00   ┆   ┆            ┆            ┆           ┆           │
│ 24     ┆ 24         ┆ 161859  ┆ 2139-06-06 ┆ … ┆ null       ┆ INTERIOR   ┆ 0         ┆ 1         │
│        ┆            ┆         ┆ 16:14:00   ┆   ┆            ┆ MYOCARDIAL ┆           ┆           │
│        ┆            ┆         ┆            ┆   ┆            ┆ INFARCTION ┆           ┆           │
│ 25     ┆ 25         ┆ 129635  ┆ 2160-11-02 ┆ … ┆ 2160-11-02 ┆ ACUTE      ┆ 0         ┆ 1         │
│        ┆            ┆         ┆ 02:06:00   ┆   ┆ 04:27:00   ┆ CORONARY   ┆           ┆           │
│        ┆            ┆         ┆            ┆   ┆            ┆ SYNDROME   ┆           ┆           │
└────────┴────────────┴─────────┴────────────┴───┴────────────┴────────────┴───────────┴───────────┘

In [ ]:
diags = pl.read_csv(
    mimic3source + "DIAGNOSES_ICD.csv",
    separator=",",
    infer_schema_length=10000
)

In [ ]:
diags.head()

shape: (5, 5)
┌────────┬────────────┬─────────┬─────────┬───────────┐
│ ROW_ID ┆ SUBJECT_ID ┆ HADM_ID ┆ SEQ_NUM ┆ ICD9_CODE │
│ ---    ┆ ---        ┆ ---     ┆ ---     ┆ ---       │
│ i64    ┆ i64        ┆ i64     ┆ i64     ┆ str       │
╞════════╪════════════╪═════════╪═════════╪═══════════╡
│ 1297   ┆ 109        ┆ 172335  ┆ 1       ┆ 40301     │
│ 1298   ┆ 109        ┆ 172335  ┆ 2       ┆ 486       │
│ 1299   ┆ 109        ┆ 172335  ┆ 3       ┆ 58281     │
│ 1300   ┆ 109        ┆ 172335  ┆ 4       ┆ 5855      │
│ 1301   ┆ 109        ┆ 172335  ┆ 5       ┆ 4254      │
└────────┴────────────┴─────────┴─────────┴───────────┘

In [ ]:
procs = pl.read_csv(
    mimic3source + "PROCEDURES_ICD.csv",
    separator=",",
    infer_schema_length=10000
)

In [ ]:
procs.head()

shape: (5, 5)
┌────────┬────────────┬─────────┬─────────┬───────────┐
│ ROW_ID ┆ SUBJECT_ID ┆ HADM_ID ┆ SEQ_NUM ┆ ICD9_CODE │
│ ---    ┆ ---        ┆ ---     ┆ ---     ┆ ---       │
│ i64    ┆ i64        ┆ i64     ┆ i64     ┆ i64       │
╞════════╪════════════╪═════════╪═════════╪═══════════╡
│ 944    ┆ 62641      ┆ 154460  ┆ 3       ┆ 3404      │
│ 945    ┆ 2592       ┆ 130856  ┆ 1       ┆ 9671      │
│ 946    ┆ 2592       ┆ 130856  ┆ 2       ┆ 3893      │
│ 947    ┆ 55357      ┆ 119355  ┆ 1       ┆ 9672      │
│ 948    ┆ 55357      ┆ 119355  ┆ 2       ┆ 331       │
└────────┴────────────┴─────────┴─────────┴───────────┘